### ISSUE TITLE
Unknow types

### ISSUE THREAD

**Issue by constantinje** [jchristn/DatabaseWrapper#10]
It will be good to retrieve unknown type as text when DataTable are returned as described here for npgsql
[Link](https://www.npgsql.org/doc/faq.html#a-nameunknowntypei-get-an-exception-the-field-field1-has-a-type-currently-unknown-to-npgsql-oid-xxxxx-you-can-retrieve-it-as-a-string-by-marking-it-as-unknowna)

**Comment by shawty** [comment]
I agree.  I've just opened an SQLite file (That I pulled from my Plex Media Server installation), ran describe database on it and got this:

![image](https://user-images.githubusercontent.com/1876454/186667313-e16dacb1-9d73-42b3-ae9b-e4605b4534b5.png)

I have no idea what a dt_integer is, never seen that data type before in all the years I've worked with SQLite, but would be good to have some way of still retrieving it in the describe functions so we can decide how we want to deal with it at app level.

**Comment by jchristn** [comment]
Hi all, I just published v4.1.5 to NuGet, which removes the exception that is thrown when an unknown datatype is encountered.  It now returns ```DataType.Unknown```.  The only obvious caveat I can think of is attempting to create a new table and setting one of the column types to ```Unknown``` (it's obvious why that exception has to remain), but this version should solve the issue.  Would you mind giving it a try?  It's up in NuGet now.

**Comment by shawty** [comment]
Will do.

Just a thought, is there some mechanism you could come up with that would fire some kind of event or action to ask for the data type to use?

In my case for example, I've found out that sqlite can use pretty much anything as a column data type name (I even tested it), but in most cases it really only understands int, blob or varchar.

My example above "dt_integer" actually turned out to be a unix epoch time stamp, so a mechanism that asks for the data type, would have seen me returning "integer" as the data type to use.

I'll give it some thought, see if I come up with any ideas, doubt I'll get a chance to code anything though, got too much other stuff to get done in the next couple of weeks.

**Comment by jchristn** [comment]
It's a great suggestion, but would take some gymnastics to get that kind of logic to the place in the code where that determination is made today.  Please re-open if the updated version doesn't allow you to continue and access your data!

**Comment by shawty** [comment]
Will do, and I'll let you know if I come up with any ideas for how said Gymnastics might work :-)
